import type { Request, Response, NextFunction } from "express";
import { getRequestId } from "./requestId";

/**
 * Correlation ID Middleware
 * 
 * - Request ID: Unique per single request (already generated by requestId middleware)
 * - Correlation ID: Unique per request chain (for cross-service tracing)
 * 
 * If upstream service sends X-Correlation-Id, we propagate it.
 * Otherwise, we use the Request ID as the Correlation ID.
 */

export const CORRELATION_ID_HEADER = "x-correlation-id";

export default function correlationIdMiddleware(req: Request, res: Response, next: NextFunction) {
    const upstreamCorrelationId = req.headers[CORRELATION_ID_HEADER] as string | undefined;
    const requestId = getRequestId(req);

    // Use upstream correlation ID if present, otherwise use request ID
    const correlationId = upstreamCorrelationId || requestId || "";

    // Attach to request for use in application code
    (req as any).correlationId = correlationId;

    // Set header for downstream services and response
    res.setHeader("X-Correlation-Id", correlationId);

    next();
}

export const getCorrelationId = (req: Request): string | undefined =>
    (req as any).correlationId as string | undefined;
